openapi: 3.0.3
info:
    title: Laravel
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths:
    /api/login:
        post:
            summary: 'Handle a login request to the application.'
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    access_token: eyJ0eXAiOiJKV1QiL...
                                    token_type: Bearer
                                    expires_at: '2022-03-12 02:49:46'
                                properties:
                                    access_token: { type: string, example: eyJ0eXAiOiJKV1QiL... }
                                    token_type: { type: string, example: Bearer }
                                    expires_at: { type: string, example: '2022-03-12 02:49:46' }
            tags:
                - Authentication
            security: []
        parameters:
            -
                in: path
                name: email
                description: ''
                example: distinctio
                required: true
                schema:
                    type: string
            -
                in: path
                name: password
                description: ''
                example: ab
                required: true
                schema:
                    type: string
    /api/user:
        get:
            summary: 'Retrive User Data.'
            description: ''
            parameters:
                -
                    in: header
                    name: Authorization
                    description: ''
                    example: 'Bearer {YOUR_AUTH_KEY}'
                    schema:
                        type: string
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    id: 0c6d672a-b0c7-4eec-9918-074b70d480b1
                                    name: Testing
                                    email: testing@gmail.com
                                    email_verified_at: null
                                    created_at: '2021-03-11T07:30:38.000000Z'
                                    updated_at: '2021-03-11T07:30:38.000000Z'
                                properties:
                                    id: { type: string, example: 0c6d672a-b0c7-4eec-9918-074b70d480b1 }
                                    name: { type: string, example: Testing }
                                    email: { type: string, example: testing@gmail.com }
                                    email_verified_at: { type: string, example: null }
                                    created_at: { type: string, example: '2021-03-11T07:30:38.000000Z' }
                                    updated_at: { type: string, example: '2021-03-11T07:30:38.000000Z' }
            tags:
                - 'User management'
components:
    securitySchemes:
        default:
            type: http
            scheme: bearer
            description: ''
security:
    -
        default: []
